name: nakama-node-1
data_dir: "./data/"

logger:
  stdout: false
  level: "warn"
  file: "data/logfile.log"

metrics:
  reporting_freq_sec: 60
  namespace: ""
  stackdriver_projectid: ""
  prometheus_port: 0 

database:
  address:
    - "root@localhost:26257"
  conn_max_lifetime_ms: 0
  max_open_conns: 0
  max_idle_conns: 100

runtime:
  env:
    - "encryptionkey=A_]&+D7♥{Ph&~-¿^g}52"
  path: "modules"
  http_key: "XiHe41dci9"

socket:
  server_key: "ZdsG11p&y13zl6a"
  port: 7350
  max_message_size_bytes: 4096 # bytes
  read_timeout_ms: 10000
  write_timeout_ms: 10000
  idle_timeout_ms: 60000
  write_wait_ms: 5000
  pong_wait_ms: 10000
  ping_period_ms: 8000 # Must be less than pong_wait_ms
  outgoing_queue_size: 16

session:
  encryption_key: "_|1[Tg0♥x&~jAU{B♦:>"
  token_expiry_sec: 259200 #Todo, some things much up and can't close properly when expiry token expires. Should renew token instead of setting high number

social:
  steam:
    publisher_key: ""
    app_id: 0

console:
  port: 7351
  username: "nowhereknowhow"
  password: "qweasd"
  signing_key: "?X&dLbIoj_JR!tB"
  idle_timeout_ms: 1000000000000

cluster:
  join:
    - "10.0.0.2:7352"
    - "10.0.0.3:7352"
  gossip_bindaddr: "0.0.0.0"
  gossip_bindport: 7352
  rpc_port: 7353